const { createChatObject } = require("../utils");

module.exports = {
  generateRawLyrics,
};

const customSystemPromptShell = (userInput) => {
  return "";
};

/**
 * Generates raw lyrics based on a specified meter and prompts.
 *
 * @async
 * @function generateRawLyrics
 * @param {Object} options - The options for generating the lyrics.
 * @param {number} options.lineLimit - The maximum number of lines for the generated lyrics.
 * @param {Array<Array<number>>} options.meter - The meter pattern for the lyrics, an array of arrays of numbers.
 * @param {string} options.selectedUserPrompt - The key for the selected user prompt.
 * @param {string} options.selectedSystemPrompt - The key for the selected system prompt.
 * @returns {Promise<Object>} The raw lyrics generated by the OpenAI API.
 * @throws Will log an error to the console if the API call fails.
 */
async function generateRawLyrics({
  lineLimit,
  meter,
  selectedUserPrompt,
  selectedSystemPrompt,
  restOfSong,
  customSystemPrompt,
  songTitle,
  songDescription,
  clientChoice = "anthropic",
}) {
  try {
    const meterString = meter
      .map(
        (pattern, index) =>
          `Line ${
            index + 1
          } will use this pattern: ${pattern.join()} and have ${
            pattern.length
          } syllables.`
      )
      .join(" ");
    const alternatingInstructions =
      meter.length > 0 ? "Make sure to use an alternating meter pattern. " : "";
    const finalString = alternatingInstructions + meterString;

    const chatCompletion = await createChatObject({
      clientChoice,
      customSystemPrompt,
      selectedSystemPrompt,
      selectedUserPrompt,
      lineLimit,
      finalString,
      restOfSong,
      songTitle,
      songDescription,
    });
    console.log(chatCompletion);

    return clientChoice === "openai"
      ? chatCompletion.choices[0].message.content
          .split("\n")
          .filter((e) => e.length > 0)
          .map((e) => e.trim())
      : chatCompletion.content[0].text
          .split("\n")
          .filter((e) => e.length > 0)
          .map((e) => e.trim());
  } catch (err) {
    console.log(err);
  }
}
